pipeline:
  clone:
    image: plugins/git
    depth: 1

  phpcs:
    image: joomlaprojects/docker-phpcs
    commands:
      - echo $(date)
      - /root/.composer/vendor/bin/phpcs --report=full --encoding=utf-8 --extensions=php -p --standard=build/phpcs/Joomla .
      - echo $(date)

  javascript:
    image: joomlaprojects/docker-systemtests:latest
    commands:
      - echo $(date)
      - apt-get install nodejs npm
      - ln -s /usr/bin/nodejs /usr/bin/node
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - cd tests/javascript
      - npm install
      - cd ../..
      - tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run
      - echo $(date)

  analysis:
    image: rips/rips-cli
    secrets:  [rips_username, rips_password]
    commands:
      - export RIPS_BASE_URI='https://api.rips.joomla.org'
      - export RIPS_USERNAME=$RIPS_USERNAME
      - export RIPS_PASSWORD=$RIPS_PASSWORD
      - rips-cli rips:scan:start  -a 1 -t 1 -p $(pwd) -t 1 -T $DRONE_REPO_OWNER-$DRONE_BRANCH ||  { echo "Please contact the security team at security@joomla.org"; exit 1; }

